### ISSUE TITLE
Cannot re-use returned results (including errors) after closing mrb

### ISSUE THREAD

**Issue by sethvargo** [mitchellh/go-mruby#12]
I don't know if this is a bug or just a general misunderstanding of how the bindings work, but consider the following:

```go
// run is a simple go function that returns a syntax error
func run() error {
	mrb := mruby.NewMrb()
	defer mrb.Close()

	_, err := mrb.LoadString(`clearly a syntax error`)
	if err != nil {
		return err
	}
	return nil
}

// Test just executes run and tries to print the result
func TestFuck(t *testing.T) {
	err := run()
	if err != nil {
		println(fmt.Sprintf("err: %s", err))
	}
}
```

This will, 100% of the time, panic. The resulting panic text does vary slightly, but they all seem to indicate that, upon closing `mrb`, any errors or return values are GCed, meaning it is not possible to blindly return an error as above in standard go-like behavior.

My current workaround is to basically copy the error:

```go
	if err != nil {
		err = errors.New(err.Error())
		return err
	}
```

Which seems pretty non-optimized.

Even using the example in the README, introducing a syntax error and invoking from another function will cause a C-level panic.

Is this intended? Any workarounds?

**Comment by mitchellh** [comment]
Ah, yeah this is "intended" in the worst possible way. it is working as should be expected: exceptions aren't valid once the Ruby context is closed, but then again this kind of hurts the UX.

I'm going to see if there is a way to detect if the Ruby context is still available. If it is, we can do the normal thing. Otherwise, we can maybe just copy the string value...

**Comment by mitchellh** [comment]
Okay I pushed a fix. There isn't a way to test if a state is closed, and we pass around the raw C pointer. So instead, we just cache the string value so it works across the close. Tested.

**Comment by sethvargo** [comment]
Thanks!
