### ISSUE TITLE
Arg specs are not enforced

### ISSUE THREAD

**Issue by sethvargo** [mitchellh/go-mruby#13]
Consider the code example from the README:

```go
addFunc := func(m *mruby.Mrb, self *mruby.MrbValue) (mruby.Value, mruby.Value) {
    args := m.GetArgs()
    return mruby.Int(args[0].Fixnum() + args[1].Fixnum()), nil
}

class := mrb.DefineClass("Example", nil)
class.DefineClassMethod("add", addFunc, mruby.ArgsReq(2))

result, err := mrb.LoadString(`Example.add(12, 30)`)
if err != nil {
    panic(err.Error())
}
```

Even though the spec says that two arguments are required, if you call the function with less than two arguments:

```go
result, err := mrb.LoadString(`Example.add(12)`)
```

it will panic (since the function is trying to access an index out of the range of the slice):

```text
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range
```

and if you give it more than 2 args:

```go
result, err := mrb.LoadString(`Example.add(12, 12, 12)`)
```

It happily adds the first two and completely ignores any other arguments.

**Comment by mitchellh** [comment]
This is going to sound funny, but I looked in the mruby source code (see `class.c`) and it looks like arg specs actually aren't used at all right now. We're passing them in properly but they just... aren't used. So this looks more like an mruby bug?

**Comment by mitchellh** [comment]
I found this TODO in the mruby source as well, which sounds relevant: `    /* TODO cfunc aspec not implemented yet */`

**Comment by sethvargo** [comment]
Wonderful :smile:
