### ISSUE TITLE
stack split when raising an exception inside of a yielded block within Go code

### ISSUE THREAD

**Issue by jsternberg** [mitchellh/go-mruby#16]
Simple reproducer added to `mruby_test.go`.

```
func TestMrbYieldException(t *testing.T) {
    mrb := NewMrb()
    defer mrb.Close()

    cb := func(m *Mrb, self *MrbValue) (Value, Value) {
        result, err := m.Yield(m.GetArgs()[0])
        if err != nil {
            exc := err.(*mruby.Exception)
            return nil, exc
        }
        return result, nil
    }

    class := mrb.DefineClass("Hello", mrb.ObjectClass())
    class.DefineClassMethod("foo", cb, ArgsBlock())
    _, err := mrb.LoadString(`Hello.foo { raise "exception" }`)
    if err == nil {
        t.Fatalf("expected err")
    }
}
```

This will consistently crash the go runtime with something like this:

```
runtime: newstack sp=0xc82003ada0 stack=[0xc82003a000, 0xc82003afd0]
        morebuf={pc:0x4092559 sp:0xc82003ada8 lr:0x0}
        sched={pc:0x409372d sp:0xc82003ada0 lr:0x0 ctxt:0x0}
```

It appears an exception might get thrown and the go -> ruby -> go -> ruby seems to cause a problem. You can also reproduce it by calling `m.LoadString("raise 'exception'")` from inside of the function call.

**Comment by mitchellh** [comment]
Reproduced. Thanks for the detailed bug report. Let me take a look at this.

**Comment by mitchellh** [comment]
Fixed! Please let me know if you find any other issues related to this, I'm sure there are more cases where this can happen that we'll have to patch up.

**Comment by jsternberg** [comment]
Thanks!
