### ISSUE TITLE
Issues compiling the go example

### ISSUE THREAD

**Issue by amoghe** [mitchellh/go-mruby#17]
I've cloned this project into `$GOPATH/src/go-mruby` and run `make`, which went swimmingly. Then I ran `go install` so that it got copied into `$GOPATH/pkg/linux_amd64`. 

Next, I created another dir an pasted the example code (from `README`) into the `main` pkg, located at `$GOPATH/src/gorbtest/main.go`. 

When I attempt to `go build` the test pkg, it complains like so:

```
/home/akshay/.gimme/versions/go1.5.1.linux.amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: libmruby.a: No such file or directory
```

I use `gimme` to manage the go version (and hence the nonstandard `$GOROOT`), but that shouldn't make a difference, correct?

My `$GOPATH` seems to have a `go-mruby.a` after I `go install` in go-mruby, so that should be used by whatever I'm trying to build, right? What am I missing?

**Comment by Seppone** [comment]
Did you try to copy libmruby.a into your project?

**Comment by jackc** [comment]
I ran into the same problem on OSX. Got this error:

```
jack@hk-47~/dev/go/src/github.com/jackc/mruby-experiment$ go run main.go
# command-line-arguments
/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
clang: error: no such file or directory: 'libmruby.a'
``` 

Copying libmruby.a into my project directory allowed it to run successfully.

Maybe this requirement could be documented, or if there is a more correct solution it could be documented.

**Comment by bmoylan** [comment]
I think I have a solution to this in #28
