### ISSUE TITLE
mrbgems defined classes unavailable?

### ISSUE THREAD

**Issue by mikesimons** [mitchellh/go-mruby#18]
Is there any trick to getting mrbgem defined classes to be available?

Adding (for instance) `conf.gem :git => 'https://github.com/iij/mruby-regexp-pcre.git'` to the build_config.rb , the `make` output reports that it should be available:

``` 
      Config Name: host
 Output Directory: build/host
         Binaries: mrbc
    Included Gems:
             mruby-erb - Direct ERB port from CRuby
             mruby-regexp-pcre
...
```

And it's available in `mirb`:
```
$ echo "Regexp.methods" | vendor/mruby/build/host/bin/mirb
mirb - Embeddable Interactive Ruby Shell

>  => [:instance_of?, :instance_eval, :_inspect, :instance_variable_get, :instance_variable_defined?, :instance_variable_set, :instance_variables, :Hash, :to_enum, :is_a?, :kind_of?, :method_missing, :protected_methods, :last_match, :`, :new, :private_methods, :initialize, :object_id, :quote, :methods, :!, :class_variable_get, :respond_to?, :attr_accessor, :send, :class_variable_defined?, :attr, :loop, :inherited, :public_methods, :remove_instance_variable, :superclass, :!=, :prepended, :prepend_features, :==, :escape, :instance_exec, :include, :__send__, :include?, :tap, :__id__, :extend_object, :proc, :iterator?, :class_variable_set, :local_variables, :raise, :prepend, :p, :extended, :singleton_class, :printf, :module_eval, :initialize_copy, :module_function, :hash, :format, :sprintf, :extend, :instance_methods, :__printstr__, :method_defined?, :equal?, :dup, :included_modules, :included, :eql?, :Integer, :srand, :rand, :class_eval, :class, :append_features, :puts, :clone, :to_s, :inspect, :alias_method, :ancestors, :const_defined?, :undef_method, :const_set, :const_get, :public, :__method__, :remove_class_variable, :private, :protected, :attr_writer, :lambda, :String, :attr_reader, :method_removed, :fail, :remove_method, :print, :block_given?, :global_variables, :enum_for, :compile, :nil?, :Array, :"!~", :class_variables, :===, :__case_eqq, :define_method, :Float, :const_missing, :singleton_methods, :remove_const, :constants, :define_singleton_method]
```

But it is not available in the mrb context created by go-mruby with the following snippet:
```
    mrb := mruby.NewMrb()
    defer mrb.Close()
    result, _ := mrb.LoadString(`Regexp.methods`)
    fmt.Printf("Result: %s\n", result.String())
```

The output is:

```
panic: uninitialized constant Regexp

goroutine 1 [running]:
main.main()
	/home/mike/go/src/github.com/mikesimons/templateer/main.go:61 +0x100

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

I appreciate this may be me being thick headed but I've successfully managed to work with mruby in C  (here https://github.com/mikesimons/templateer) and go-mruby is not behaving as the C counterpart does even though initialization steps seem to be (more or less) the same.

In the C version above, mrbgem defined classes are simply available as if they were part of stdlib.

**Comment by mikesimons** [comment]
Ok, I figured it out. I was expecting to be able to build `libmruby.a` in my project dir and have the `build_config.rb` stuff self contained but that does not appear to be how this works.

To get it to work I had to copy my `build_config.rb` to the `go-mruby/vendor/mruby` directory, run `make` in the `go-mruby` directory and then copy `libmruby.a` to my project dir. This made all gem classes available.

Simply linking in a customized `libmruby.a` does not work (I have not dug deep enough to discover why not but I expect fundamental misunderstanding of how go builds work on my part).

If I haven't missed anything then this means that only one concurrent build of go-mruby with customized gems can happen at a time as they will all need to rebuild `libmruby.a` and `go-mruby` each time which seems like a pretty severe limitation.

The only way around this that springs to mind is to vendor `go-mruby` in my project directory.

If anyone has any thoughts on this or can point me to my misunderstanding I would be very appreciative.

**Comment by mikesimons** [comment]
Last one from me on this unless someone chimes in to tell me what I've missed. There is a [template project over here](https://github.com/mikesimons/go-mruby-template) that should provide enough to get started.

I doubt it's the best way of doing things but it does work (at least on linux) and enables a self contained project / workflow.

**Comment by mitchellh** [comment]
Sorry @mikesimons for the lack of a response. I still haven't had a chance to read this but it looks like you're making some great progress. I'll try to read this soon!

**Comment by mikesimons** [comment]
@mitchellh No worries; I imagine you're pretty busy these days and this isn't exactly a high priority repo ;)
It's pretty much solved as far as I need it solving now but if you have any input or recommendations I'd love to hear them.

**Comment by mikesimons** [comment]
@mitchellh Nothing to do for this one unless you'd like to reference the template project in the README or have some other idea on how projects can use go-mruby without vendoring. Feel free to close.

**Comment by erikh** [comment]
are you still seeing this? I have this in my makefile and it works on latest master:

https://github.com/erikh/box/blob/master/Makefile#L4

**Comment by mikesimons** [comment]
@erikh No; vendoring solved my issue. We should probably point out in the readme that any potential users should vendor go-mruby though or all projects will be sharing the libmruby.a from `$GOPATH/src/github.com/mitchellh/go-mruby`.

**Comment by erikh** [comment]
Ok, I'll submit a patch tomorrow night. SGTM. Should we close this?
