### ISSUE TITLE
After successful install and testing I get 'could not determine kind of name for C.mrb_ary_len'

### ISSUE THREAD

**Issue by lostinblue** [mitchellh/go-mruby#68]
```
src/github.com/mitchellh/go-mruby/array.go:15:13: could not determine kind of name for C.mrb_ary_len
```

Anyone run into this before?

**Comment by erikh** [comment]
this is a part of the problem with #66 . You'll need to use the 1.2.0 tag or earlier to use go-mruby at the moment. I'm working on a patch but it's going slow; a lot of changes have happened.

**Comment by erikh** [comment]
I'm going to close this; track #66 if you want to follow up on these changes please. Thanks!
